version: '3.8'

x-airflow-image: &airflow-image
    image: airflow-development:latest
    restart: "no"
    user: "${UID:-50000}:0"
    build: 
        context: .
        dockerfile: ./Dockerfile
    depends_on:
        - postgres
    volumes:
        - ./dags:/opt/airflow/dags
        - airflow_logs:/opt/airflow/logs
    environment:
        - AIRFLOW__CORE__PARALLELISM=4
        - AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG=16
        - AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG=16
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor  # Tambahkan ini jika ingin pakai LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow

services:
    postgres:
        image: postgres:13
        container_name: airflow-postgres-tt
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - postgres_data:/var/lib/postgresql/data/pgdata

    airflow-init:
        <<: *airflow-image
        container_name: airflow-init
        entrypoint: >
            /bin/bash -c "
            airflow db init &&
            airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
            "

    airflow-webserver:
        <<: *airflow-image
        container_name: airflow-webserver-tt
        ports:
            - "8080:8080"
            - "8793:8793"
        depends_on:
            - airflow-init
        command: airflow webserver

    airflow-scheduler:
        <<: *airflow-image
        container_name: airflow-scheduler-tt
        depends_on:
            - airflow-init
        command: airflow scheduler

volumes:
    postgres_data:
    airflow_logs:
